version: '2'

services:
    task_api:
      container_name: task-api
      image: task-management-api:1.0.0
      volumes:
        - ./config.yaml:/usr/src/app/config.yaml
        - ./logger.conf:/usr/src/app/logger.conf
        - ./logs:/usr/src/app/logs
      environment:
        PORT: 8080
        WORKER: 1
        METRICS_PORT: 18080
        prometheus_multiproc_dir: /tmp

      ports:
        - 8086:8080